Bootstrap: docker
From: python:3.8-alpine

%labels
    AUTHOR icaoberg, luism
    EMAIL icaoberg@psc.edu, luism@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://gitub.com/pscedu/singularity-visidata
    COPYRIGHT Copyright (c) 2024-2025 Pittsburgh Supercomputing Center. All Rights Reserved.   
    VERSION 3.2

%environment
    export TERM="xterm-256color"

%post
    apk update
    apk add git man-pages mandoc
    pip install requests python-dateutil wcwidth tabulate
    mkdir -p /opt/visidata
    git clone https://github.com/saulpw/visidata.git
    cd visidata
    git checkout tags/v3.2
    sh -c 'yes | pip install -vvv .'
    rm -rfv visidata

%runscript
    vd "$@"
